#! /usr/bin/env node

// Get arguments passed on command line
const userArgs = process.argv.slice(2);

const mongoose = require("mongoose");
mongoose.set("strictQuery", false);

const mongoDB = userArgs[0];

main().catch((err) => console.log(err));

const Item = require("./models/item");
const Banner = require("./models/banner");

async function main() {
  console.log("Debug: About to connect");
  try {
    await mongoose.connect(mongoDB);
    console.log("Debug: Connected to MongoDB");
    await createItems();
    await createBanners();
  } catch (error) {
    console.error("Error connecting to MongoDB:", error);
  } finally {
    console.log("Debug: Closing mongoose");
    mongoose.connection.close();
  }
}

async function createItems() {
  for (let object of seeds) {
    const item = new Item(object);
    item.tags = createTags(object);
    await item.save();
  }
}

async function createBanners() {
  for (let object of banners) {
    const banner = new Banner(object);
    await banner.save();
  }
}

function createTags(seed) {
  let tags = "";
  for (const [key, value] of Object.entries(seed)) {
    if (key === "price") break;
    tags += " " + value.toLowerCase();
  }
  return tags;
}

var seeds = [
  {
    name: "Colorful Marigold Seeds",
    plant_type: "Flowers",
    growing_season: "Spring",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 283,
  },
  {
    name: "Organic Cabbage Seeds",
    plant_type: "Vegetables",
    growing_season: "Fall",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Non-GMO Chives Seeds",
    plant_type: "Herbs",
    growing_season: "Summer",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Rare Specialty Orange Tree Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 847,
  },
  {
    name: "Native Blueberry Bush Seeds",
    plant_type: "Shrubs",
    growing_season: "Spring",
    seed_varieties: "Native Species",
    planting_location: "Outdoor",
    special_attributes: "Shade-Tolerant",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 452,
  },
  {
    name: "Drought-Tolerant Bermuda Grass Seeds",
    plant_type: "Grasses",
    growing_season: "Summer",
    seed_varieties: "Non-GMO",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 113,
  },
  {
    name: "Heirloom Daisy Seeds",
    plant_type: "Flowers",
    growing_season: "Summer",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 339,
  },
  {
    name: "Organic Spinach Seeds",
    plant_type: "Vegetables",
    growing_season: "Fall",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Wildlife-Attracting Lemongrass Seeds",
    plant_type: "Herbs",
    growing_season: "Summer",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Pollinator-Friendly Cherry Tree Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 678,
  },
  {
    name: "Fragrant Lavender Seeds",
    plant_type: "Flowers",
    growing_season: "Summer",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 226,
  },
  {
    name: "Juicy Tomato Seeds",
    plant_type: "Vegetables",
    growing_season: "Summer",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 452,
  },
  {
    name: "Aromatic Mint Seeds",
    plant_type: "Herbs",
    growing_season: "Spring",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Sweet Apple Tree Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 847,
  },
  {
    name: "Vibrant Rhododendron Seeds",
    plant_type: "Shrubs",
    growing_season: "Summer",
    seed_varieties: "Native Species",
    planting_location: "Outdoor",
    special_attributes: "Shade-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 565,
  },
  {
    name: "Sturdy Bamboo Seeds",
    plant_type: "Grasses",
    growing_season: "Fall",
    seed_varieties: "Non-GMO",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 282,
  },
  {
    name: "Sunny Sunflower Seeds",
    plant_type: "Flowers",
    growing_season: "Summer",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 339,
  },
  {
    name: "Crunchy Carrot Seeds",
    plant_type: "Vegetables",
    growing_season: "Fall",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Fragrant Rosemary Seeds",
    plant_type: "Herbs",
    growing_season: "Summer",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Peachy Peach Tree Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 678,
  },
  {
    name: "Tulip Delight Flower Seeds",
    plant_type: "Flowers",
    growing_season: "Spring",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 283,
  },
  {
    name: "Healthy Broccoli Seeds",
    plant_type: "Vegetables",
    growing_season: "Fall",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Fragrant Sage Seeds",
    plant_type: "Herbs",
    growing_season: "Summer",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Delicious Pear Tree Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 847,
  },
  {
    name: "Vibrant Lilac Bush Seeds",
    plant_type: "Shrubs",
    growing_season: "Summer",
    seed_varieties: "Native Species",
    planting_location: "Outdoor",
    special_attributes: "Shade-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 565,
  },
  {
    name: "Green Bamboo Shoot Seeds",
    plant_type: "Grasses",
    growing_season: "Fall",
    seed_varieties: "Non-GMO",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 282,
  },
  {
    name: "Sunny Day Sunflower Seeds",
    plant_type: "Flowers",
    growing_season: "Summer",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 339,
  },
  {
    name: "Fresh Bell Pepper Seeds",
    plant_type: "Vegetables",
    growing_season: "Fall",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Scented Thyme Seeds",
    plant_type: "Herbs",
    growing_season: "Summer",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Juicy Pomegranate Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 678,
  },
  {
    name: "Radiant Roses Seeds",
    plant_type: "Flowers",
    growing_season: "Spring",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 283,
  },
  {
    name: "Zesty Zucchini Seeds",
    plant_type: "Vegetables",
    growing_season: "Summer",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Aromatic Basil Seeds",
    plant_type: "Herbs",
    growing_season: "Spring",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Cherry Blossom Delight Tree Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 847,
  },
  {
    name: "Exquisite Azalea Seeds",
    plant_type: "Shrubs",
    growing_season: "Summer",
    seed_varieties: "Native Species",
    planting_location: "Outdoor",
    special_attributes: "Shade-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 565,
  },
  {
    name: "Tropical Palm Bamboo Seeds",
    plant_type: "Grasses",
    growing_season: "Fall",
    seed_varieties: "Non-GMO",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 282,
  },
  {
    name: "Sunny Day Lily Seeds",
    plant_type: "Flowers",
    growing_season: "Summer",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 339,
  },
  {
    name: "Sweet Crunchy Carrot Seeds",
    plant_type: "Vegetables",
    growing_season: "Fall",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Scented Rosemary Seeds",
    plant_type: "Herbs",
    growing_season: "Summer",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Peachy Delight Peach Tree Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 678,
  },
  {
    name: "Vivid Iris Flower Seeds",
    plant_type: "Flowers",
    growing_season: "Spring",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 283,
  },
  {
    name: "Healthy Cucumber Seeds",
    plant_type: "Vegetables",
    growing_season: "Summer",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Aromatic Oregano Seeds",
    plant_type: "Herbs",
    growing_season: "Spring",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Exotic Mango Tree Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 847,
  },
  {
    name: "Vibrant Azalea Bush Seeds",
    plant_type: "Shrubs",
    growing_season: "Summer",
    seed_varieties: "Native Species",
    planting_location: "Outdoor",
    special_attributes: "Shade-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 565,
  },
  {
    name: "Healthy Wheat Grass Seeds",
    plant_type: "Grasses",
    growing_season: "Fall",
    seed_varieties: "Non-GMO",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 282,
  },
  {
    name: "Sunshine Marigold Seeds",
    plant_type: "Flowers",
    growing_season: "Summer",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 339,
  },
  {
    name: "Crispy Lettuce Seeds",
    plant_type: "Vegetables",
    growing_season: "Fall",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Scented Lavender Seeds",
    plant_type: "Herbs",
    growing_season: "Summer",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Sweet Cherry Blossom Tree Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 678,
  },
  {
    name: "Dazzling Daffodil Seeds",
    plant_type: "Flowers",
    growing_season: "Spring",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 283,
  },
  {
    name: "Crunchy Bell Pepper Seeds",
    plant_type: "Vegetables",
    growing_season: "Summer",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Fragrant Lemongrass Seeds",
    plant_type: "Herbs",
    growing_season: "Spring",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Juicy Watermelon Seeds",
    plant_type: "Fruits",
    growing_season: "Summer",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 847,
  },
  {
    name: "Colorful Hydrangea Seeds",
    plant_type: "Shrubs",
    growing_season: "Summer",
    seed_varieties: "Native Species",
    planting_location: "Outdoor",
    special_attributes: "Shade-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 565,
  },
  {
    name: "Wholesome Quinoa Seeds",
    plant_type: "Grasses",
    growing_season: "Fall",
    seed_varieties: "Non-GMO",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 282,
  },
  {
    name: "Sun-Kissed Sunflower Seeds",
    plant_type: "Flowers",
    growing_season: "Summer",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 339,
  },
  {
    name: "Fresh Spinach Seeds",
    plant_type: "Vegetables",
    growing_season: "Fall",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Soothing Chamomile Seeds",
    plant_type: "Herbs",
    growing_season: "Summer",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Tropical Mango Tree Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 678,
  },
  {
    name: "Radiant Rose Seeds",
    plant_type: "Flowers",
    growing_season: "Spring",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 283,
  },
  {
    name: "Crunchy Celery Seeds",
    plant_type: "Vegetables",
    growing_season: "Summer",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Scented Cilantro Seeds",
    plant_type: "Herbs",
    growing_season: "Spring",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Juicy Peach Tree Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 847,
  },
  {
    name: "Vibrant Viburnum Seeds",
    plant_type: "Shrubs",
    growing_season: "Summer",
    seed_varieties: "Native Species",
    planting_location: "Outdoor",
    special_attributes: "Shade-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 565,
  },
  {
    name: "Wholesome Wheat Seeds",
    plant_type: "Grasses",
    growing_season: "Fall",
    seed_varieties: "Non-GMO",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 282,
  },
  {
    name: "Sunny Daisy Seeds",
    plant_type: "Flowers",
    growing_season: "Summer",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 339,
  },
  {
    name: "Fresh Broccoli Seeds",
    plant_type: "Vegetables",
    growing_season: "Fall",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Scented Mint Seeds",
    plant_type: "Herbs",
    growing_season: "Summer",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Sweet Apple Orchard Tree Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 678,
  },
  {
    name: "Golden Marigold Seeds",
    plant_type: "Flowers",
    growing_season: "Spring",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 283,
  },
  {
    name: "Crisp Lettuce Seeds",
    plant_type: "Vegetables",
    growing_season: "Summer",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Aromatic Thyme Seeds",
    plant_type: "Herbs",
    growing_season: "Spring",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Sweet Orange Tree Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 847,
  },
  {
    name: "Radiant Rhododendron Seeds",
    plant_type: "Shrubs",
    growing_season: "Summer",
    seed_varieties: "Native Species",
    planting_location: "Outdoor",
    special_attributes: "Shade-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 565,
  },
  {
    name: "Healthy Barley Seeds",
    plant_type: "Grasses",
    growing_season: "Fall",
    seed_varieties: "Non-GMO",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 282,
  },
  {
    name: "Sunrise Sunflower Seeds",
    plant_type: "Flowers",
    growing_season: "Summer",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 339,
  },
  {
    name: "Fresh Bell Pepper Garden Seeds",
    plant_type: "Vegetables",
    growing_season: "Fall",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Scented Eucalyptus Seeds",
    plant_type: "Herbs",
    growing_season: "Summer",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Sweet Plum Tree Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 678,
  },
  {
    name: "Vibrant Violet Orchid Seeds",
    plant_type: "Flowers",
    growing_season: "Spring",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 283,
  },
  {
    name: "Crispy Spinach Seeds",
    plant_type: "Vegetables",
    growing_season: "Summer",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Minty Peppermint Seeds",
    plant_type: "Herbs",
    growing_season: "Spring",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Sweet Banana Tree Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 847,
  },
  {
    name: "Blooming Bougainvillea Seeds",
    plant_type: "Shrubs",
    growing_season: "Summer",
    seed_varieties: "Native Species",
    planting_location: "Outdoor",
    special_attributes: "Shade-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 565,
  },
  {
    name: "Wholesome Wheatgrass Seeds",
    plant_type: "Grasses",
    growing_season: "Fall",
    seed_varieties: "Non-GMO",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 282,
  },
  {
    name: "Sunny Sunflower Bloom Seeds",
    plant_type: "Flowers",
    growing_season: "Summer",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 339,
  },
  {
    name: "Fresh Carrot Patch Seeds",
    plant_type: "Vegetables",
    growing_season: "Fall",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Scented Lavender Fields Seeds",
    plant_type: "Herbs",
    growing_season: "Summer",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Juicy Mango Orchard Tree Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 678,
  },
  {
    name: "Royal Bluebell Seeds",
    plant_type: "Flowers",
    growing_season: "Spring",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 283,
  },
  {
    name: "Crispy Kale Seeds",
    plant_type: "Vegetables",
    growing_season: "Summer",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Refreshing Peppermint Seeds",
    plant_type: "Herbs",
    growing_season: "Spring",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Sweet Raspberry Bush Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 847,
  },
  {
    name: "Vibrant Viburnum Hedge Seeds",
    plant_type: "Shrubs",
    growing_season: "Summer",
    seed_varieties: "Native Species",
    planting_location: "Outdoor",
    special_attributes: "Shade-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 565,
  },
  {
    name: "Wholesome Wild Rice Seeds",
    plant_type: "Grasses",
    growing_season: "Fall",
    seed_varieties: "Non-GMO",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 282,
  },
  {
    name: "Sunburst Sunflower Seeds",
    plant_type: "Flowers",
    growing_season: "Summer",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 339,
  },
  {
    name: "Fresh Zucchini Seeds",
    plant_type: "Vegetables",
    growing_season: "Fall",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Scented Lemongrass Fields Seeds",
    plant_type: "Herbs",
    growing_season: "Summer",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Sweet Cherry Orchard Tree Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 678,
  },
  {
    name: "Eternal Echinacea Seeds",
    plant_type: "Flowers",
    growing_season: "Spring",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 283,
  },
  {
    name: "Crispy Cauliflower Seeds",
    plant_type: "Vegetables",
    growing_season: "Summer",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Soothing Sage Seeds",
    plant_type: "Herbs",
    growing_season: "Spring",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Juicy Blueberry Bush Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 847,
  },
  {
    name: "Vibrant Verbena Seeds",
    plant_type: "Shrubs",
    growing_season: "Summer",
    seed_varieties: "Native Species",
    planting_location: "Outdoor",
    special_attributes: "Shade-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 565,
  },
  {
    name: "Wholesome Wildflower Mix Seeds",
    plant_type: "Grasses",
    growing_season: "Fall",
    seed_varieties: "Non-GMO",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 282,
  },
  {
    name: "Sunlit Sunflower Patch Seeds",
    plant_type: "Flowers",
    growing_season: "Summer",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 339,
  },
  {
    name: "Fresh Bell Pepper Medley Seeds",
    plant_type: "Vegetables",
    growing_season: "Fall",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Scented Lavender Breeze Seeds",
    plant_type: "Herbs",
    growing_season: "Summer",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Sweet Citrus Grove Tree Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 678,
  },
  {
    name: "Mystic Morning Glory Seeds",
    plant_type: "Flowers",
    growing_season: "Spring",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 283,
  },
  {
    name: "Crispy Carrot Seeds",
    plant_type: "Vegetables",
    growing_season: "Summer",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Soothing Lavender Seeds",
    plant_type: "Herbs",
    growing_season: "Spring",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Juicy Papaya Tree Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 847,
  },
  {
    name: "Vibrant Viburnum Bloom Seeds",
    plant_type: "Shrubs",
    growing_season: "Summer",
    seed_varieties: "Native Species",
    planting_location: "Outdoor",
    special_attributes: "Shade-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 565,
  },
  {
    name: "Wholesome Quinoa Harvest Seeds",
    plant_type: "Grasses",
    growing_season: "Fall",
    seed_varieties: "Non-GMO",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 282,
  },
  {
    name: "Sunset Sunflower Meadow Seeds",
    plant_type: "Flowers",
    growing_season: "Summer",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 339,
  },
  {
    name: "Fresh Bell Pepper Rainbow Seeds",
    plant_type: "Vegetables",
    growing_season: "Fall",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Scented Lemongrass Oasis Seeds",
    plant_type: "Herbs",
    growing_season: "Summer",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Sweet Plum Grove Tree Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 678,
  },
  {
    name: "Mystical Moonflower Seeds",
    plant_type: "Flowers",
    growing_season: "Spring",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 283,
  },
  {
    name: "Crunchy Cucumber Seeds",
    plant_type: "Vegetables",
    growing_season: "Summer",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Soothing Chamomile Seeds",
    plant_type: "Herbs",
    growing_season: "Spring",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Juicy Pineapple Tree Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 847,
  },
  {
    name: "Vibrant Violet Verbena Seeds",
    plant_type: "Shrubs",
    growing_season: "Summer",
    seed_varieties: "Native Species",
    planting_location: "Outdoor",
    special_attributes: "Shade-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 565,
  },
  {
    name: "Wholesome Wheat Harvest Seeds",
    plant_type: "Grasses",
    growing_season: "Fall",
    seed_varieties: "Non-GMO",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 282,
  },
  {
    name: "Sunrise Sunflower Oasis Seeds",
    plant_type: "Flowers",
    growing_season: "Summer",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 339,
  },
  {
    name: "Fresh Eggplant Delight Seeds",
    plant_type: "Vegetables",
    growing_season: "Fall",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Scented Rosemary Fields Seeds",
    plant_type: "Herbs",
    growing_season: "Summer",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Sweet Apricot Grove Tree Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 678,
  },
  {
    name: "Mystical Morning Mist Seeds",
    plant_type: "Flowers",
    growing_season: "Spring",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 283,
  },
  {
    name: "Crispy Cornucopia Seeds",
    plant_type: "Vegetables",
    growing_season: "Summer",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Soothing Spearmint Seeds",
    plant_type: "Herbs",
    growing_season: "Spring",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Juicy Mango Orchard Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 847,
  },
  {
    name: "Vibrant Violet Viburnum Seeds",
    plant_type: "Shrubs",
    growing_season: "Summer",
    seed_varieties: "Native Species",
    planting_location: "Outdoor",
    special_attributes: "Shade-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 565,
  },
  {
    name: "Wholesome Wheatgrass Haven Seeds",
    plant_type: "Grasses",
    growing_season: "Fall",
    seed_varieties: "Non-GMO",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 282,
  },
  {
    name: "Sunlit Sunflower Haven Seeds",
    plant_type: "Flowers",
    growing_season: "Summer",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 339,
  },
  {
    name: "Fresh Radish Delight Seeds",
    plant_type: "Vegetables",
    growing_season: "Fall",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Scented Lemon Balm Fields Seeds",
    plant_type: "Herbs",
    growing_season: "Summer",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Sweet Pomegranate Grove Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 678,
  },
  {
    name: "Enchanted Evening Primrose Seeds",
    plant_type: "Flowers",
    growing_season: "Spring",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 283,
  },
  {
    name: "Crunchy Carrot Delight Seeds",
    plant_type: "Vegetables",
    growing_season: "Summer",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Soothing Lavender Oasis Seeds",
    plant_type: "Herbs",
    growing_season: "Spring",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Juicy Peach Orchard Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 847,
  },
  {
    name: "Vibrant Violet Verbena Bliss Seeds",
    plant_type: "Shrubs",
    growing_season: "Summer",
    seed_varieties: "Native Species",
    planting_location: "Outdoor",
    special_attributes: "Shade-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 565,
  },
  {
    name: "Wholesome Wildflower Symphony Seeds",
    plant_type: "Grasses",
    growing_season: "Fall",
    seed_varieties: "Non-GMO",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 282,
  },
  {
    name: "Sunrise Sunflower Harmony Seeds",
    plant_type: "Flowers",
    growing_season: "Summer",
    seed_varieties: "Heirloom",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Direct Sowing",
    package_size: "Individual Packets",
    price: 339,
  },
  {
    name: "Fresh Cucumber Medley Seeds",
    plant_type: "Vegetables",
    growing_season: "Fall",
    seed_varieties: "Organic",
    planting_location: "Outdoor",
    special_attributes: "Drought-Tolerant",
    planting_method: "Direct Sowing",
    package_size: "Bulk or Wholesale",
    price: 226,
  },
  {
    name: "Scented Rosemary Haven Seeds",
    plant_type: "Herbs",
    growing_season: "Summer",
    seed_varieties: "Non-GMO",
    planting_location: "Indoor",
    special_attributes: "Wildlife-Attracting",
    planting_method: "Transplanting",
    package_size: "Individual Packets",
    price: 170,
  },
  {
    name: "Sweet Apple Orchard Serenade Seeds",
    plant_type: "Fruits",
    growing_season: "Spring",
    seed_varieties: "Rare or Specialty",
    planting_location: "Outdoor",
    special_attributes: "Pollinator-Friendly",
    planting_method: "Transplanting",
    package_size: "Bulk or Wholesale",
    price: 678,
  },
];

var banners = [
  {
    banner_name: "placeholder",
    image_link: "https://placehold.co/900x400",
    banner_link: "/"
  },
  {
    banner_name: "placeholder",
    image_link: "https://placehold.co/900x400",
    banner_link: "/"
  },
  {
    banner_name: "placeholder",
    image_link: "https://placehold.co/900x400",
    banner_link: "/"
  },
]